version: '3.8'
services:
  redis: 
    image: redis
    ports:
      - "6389:6379"
    command: ["redis-server"]

  app:
    build: .
    container_name: node-app
    ports:
      - "4040:4040"
    depends_on:
      - redis
    environment:
     - PORT=4040
     - REDIS_PORT=6379
     - REDIS_HOST= redis